### ISSUE TITLE
PHP Fatal error:  Call to undefined function wp()

### ISSUE THREAD

**Issue by sidimar** [goodguyry/goodguyry.me#1]
Hello, 
I've followed the Multi-Tenant WordPress post and when I try access the URL "mysite.com/wordpress" I get this message **PHP Fatal error: Call to undefined function wp()** on error.log
I am using WP 4.5.3
So please, do you have any idea how to fix that?
Many thanks.

**Comment by goodguyry** [comment]
What's in your `wp-config.php` file(s) (omit the database info)?

**Comment by sidimar** [comment]
Hi, thank for your answer. I took some print screen.

Tenant wp-config.php
![wp-config-tenant](https://cloud.githubusercontent.com/assets/575328/17815667/3cb55c40-662d-11e6-80e7-e0b7ec85f844.png)

Main wp-config.php
![wp-config](https://cloud.githubusercontent.com/assets/575328/17815666/3ca8af54-662d-11e6-8fac-79514fd2b809.png)

**Comment by goodguyry** [comment]
It may have something to do with using `localhost:8181`, since the script gets the tenant's wp-config filename from the host name. I mention that in the post, but I definitely didn't make that very clear and can understand how it would be overlooked.

Try it with a virtual host and see if that fixes it. For example, if your site is at example.com, your tenant wp-config filename would need to be `example-config.php`.

**Comment by goodguyry** [comment]
I thought I had it figured out, but had another look at your main `wp-config.php` and it should work.

The only other thing I can think of is making sure all of your paths are correct and that WordPress knows where to find itself. Specifically the "Give WordPress its own directory" section.

http://goodguyry.me/notes/multi-tenant-wordpress.html

**Comment by sidimar** [comment]
Thanks a million for your help. It's helped a lot. I started again step by step and instead replace all wp-config.php I just edited where I wanted and it's work.
Nice  post and really good solution.
